# Generated by Django 2.2.16 on 2022-09-19 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_add_model_comments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='created',
            field=models.DateTimeField(auto_now_add=True, help_text='Hе меньше 10 символов.', verbose_name='Дата создания'),
        ),
    ]
