# Generated by Django 2.2.19 on 2022-08-10 08:22

import django.db.models.manager
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_auto_20220810_1231'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-pub_date']},
        ),
        migrations.AlterModelManagers(
            name='post',
            managers=[
                ('groups', django.db.models.manager.Manager()),
            ],
        ),
    ]
